Repository tlm-solutions/datacare, pull requests merged in 2023-03, with the labels that each got.

#14 fix some swagger errors
  src/routes/auth.rs
  src/routes/region.rs
  src/routes/trekkie_runs.rs
  src/routes/user.rs
Labels: bug

#15 TrekkieRun Delete Endpoint
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/routes/auth.rs
  src/routes/mod.rs
  src/routes/region.rs
  src/routes/station.rs
  src/routes/trekkie_runs.rs
  src/routes/user.rs
Labels: enhancement

#16 upgrading tlms.rs version
  Cargo.lock
  src/routes/trekkie_runs.rs
  src/routes/user.rs
Labels: bug, enhancement

#20 Fixing existing code
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  flake.lock
  src/main.rs
  src/routes/auth.rs
  src/routes/region.rs
  src/routes/station.rs
  src/routes/trekkie_runs.rs
  src/routes/user.rs
Labels: bug, enhancement

#21 Permission Endpoints
  CHANGELOG.md
  Cargo.lock
  src/main.rs
  src/routes/mod.rs
  src/routes/station.rs
  src/routes/user.rs
Labels: enhancement

#23 adding very verbose annotations
  Cargo.lock
  flake.lock
  src/main.rs
  src/routes/organization.rs
  src/routes/region.rs
  src/routes/station.rs
  src/routes/user.rs
  tests/vm/postgres.nix
  tests/vm/test-pw
Labels: enhancement
